spring:
  application:
    name: nacos-provider
    nacos:
      discovery:
        server-addr: localhost:8848
#      config:
#        server-addr: localhost:8848
#        file-extension: yaml
server:
  port: 10006
